### PR TITLE
chore: delete owlbot.py

### PR DESCRIPTION
**Pull request by parthea**
Now that googleapis/synthtool#1244 is merged, owlbot.py is no longer required in this repo. We can add owlbot.py back in the future if repository specific customizations are needed.

### CODE REVIEW

**Comment by parthea** [comment]
This repo has a slightly different owlbot.py due to the `custom_samples_dockerfile` parameter here.
https://github.com/googleapis/python-recaptcha-enterprise/blob/main/owlbot.py#L42

**Comment by parthea** [comment]
Wait for https://github.com/googleapis/synthtool/pull/1277

**Comment by parthea** [comment]
googleapis/synthtool#1277 was merged

**Comment by parthea** [comment]
This is ready for review

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
